name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v3.4.0
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
    # Artifact name
        name: programa
      
    - name: Docker Login
      uses: docker/login-action@v3.2.0
      with:
        username: bmsousa2
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
        
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.3.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: bmsousa2/aws-go-api-docker-cicd-pipeline:${{github.ref_name}}
